alert("hello")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")
console.log("NEW CONSOLE LOG")

